import random
import tkinter as tk
from tkinter import messagebox
import random

words = [
{"spanish": "Configuración", "english": "Settings"},
{"spanish": "Idioma", "english": "Language"},
{"spanish": "Pantalla", "english": "Display"},
{"spanish": "Brillo", "english": "Brightness"},
{"spanish": "Sonido", "english": "Sound"},
{"spanish": "Notificaciones", "english": "Notifications"},
{"spanish": "Batería", "english": "Battery"},
{"spanish": "Conexiones", "english": "Connections"},
{"spanish": "Almacenamiento", "english": "Storage"},
{"spanish": "Seguridad", "english": "Security"},
{"spanish": "Contraseña", "english": "Password"},
{"spanish": "Actualizaciones", "english": "Updates"},
{"spanish": "Aplicaciones", "english": "Applications (Apps)"},
{"spanish": "Permisos", "english": "Permissions"},
{"spanish": "Desinstalar", "english": "Uninstall"},
{"spanish": "Forzar detención", "english": "Force Stop"},
{"spanish": "Wi-Fi", "english": "Wi-Fi"},
{"spanish": "Datos móviles", "english": "Mobile Data"},
{"spanish": "Bluetooth", "english": "Bluetooth"},
{"spanish": "Modo avión", "english": "Airplane Mode"},
{"spanish": "Punto de acceso", "english": "Hotspot"},
{"spanish": "Red móvil", "english": "Mobile Network"},
{"spanish": "Bloqueo de pantalla", "english": "Screen Lock"},
{"spanish": "Fondo de pantalla", "english": "Wallpaper"},
{"spanish": "Tema", "english": "Theme"},
{"spanish": "Teclado", "english": "Keyboard"},
{"spanish": "Iconos", "english": "Icons"},
{"spanish": "Rotación automática", "english": "Auto-Rotate"},
{"spanish": "Privacidad", "english": "Privacy"},
{"spanish": "Huella digital", "english": "Fingerprint"},
{"spanish": "Reconocimiento facial", "english": "Facial Recognition"},
{"spanish": "Encriptación", "english": "Encryption"},
{"spanish": "Cámara", "english": "Camera"},
{"spanish": "Galería", "english": "Gallery"},
{"spanish": "Archivos", "english": "Files"},
{"spanish": "Navegador", "english": "Browser"},
{"spanish": "Correo", "english": "Email"},
{"spanish": "Modo oscuro", "english": "Dark Mode"},
{"spanish": "Hora", "english": "Time"},
{"spanish": "Reiniciar", "english": "Restart"},
{"spanish": "Apagar", "english": "Power Off"},
{"spanish": "Sonido de llamada", "english": "Ringtone"},
{"spanish": "Vibración", "english": "Vibration"},
{"spanish": "Multimedia", "english": "Multimedia"},
{"spanish": "Ajustes avanzados", "english": "Advanced Settings"},
{"spanish": "Seguridad y emergencia", "english": "Security and Emergency"},
{"spanish": "Cuentas", "english": "Accounts"},
{"spanish": "Restablecer", "english": "Reset"},
{"spanish": "Sincronización", "english": "Sync"},
{"spanish": "Copias de seguridad", "english": "Backup"},
{"spanish": "Hola, ¿cómo estás?", "english": "Hello, how are you?"},
{"spanish": "Buenos días", "english": "Good morning"},
{"spanish": "Buenas tardes", "english": "Good afternoon"},
{"spanish": "Buenas noches", "english": "Good evening/night"},
{"spanish": "Gracias", "english": "Thank you"},
{"spanish": "De nada", "english": "You're welcome"},
{"spanish": "Por favor", "english": "Please"},
{"spanish": "Lo siento", "english": "I'm sorry"},
{"spanish": "Disculpe", "english": "Excuse me"},
{"spanish": "No entiendo", "english": "I don't understand"},
{"spanish": "¿Puede repetir?", "english": "Can you repeat?"},
{"spanish": "¿Dónde está el baño?", "english": "Where is the bathroom?"},
{"spanish": "¿Cuánto cuesta?", "english": "How much does it cost?"},
{"spanish": "¿Habla inglés?", "english": "Do you speak English?"},
{"spanish": "No hablo español", "english": "I don't speak Spanish"},
{"spanish": "Ayuda, por favor", "english": "Help, please"},
{"spanish": "Estoy perdido/a", "english": "I'm lost"},
{"spanish": "¿Qué hora es?", "english": "What time is it?"},
{"spanish": "Hasta luego", "english": "See you later"},
{"spanish": "Adiós", "english": "Goodbye"},
{"spanish": "Te quiero", "english": "I love you"},
{"spanish": "¿Cómo te llamas?", "english": "What is your name?"},
{"spanish": "Me llamo...", "english": "My name is..."},
{"spanish": "¿De dónde eres?", "english": "Where are you from?"},
{"spanish": "Soy de...", "english": "I'm from..."},
{"spanish": "Tengo hambre", "english": "I'm hungry"},
{"spanish": "Tengo sed", "english": "I'm thirsty"},
{"spanish": "Estoy cansado/a", "english": "I'm tired"},
{"spanish": "Estoy feliz", "english": "I'm happy"},
{"spanish": "Estoy triste", "english": "I'm sad"},
{"spanish": "¿Puedes ayudarme?", "english": "Can you help me?"},
{"spanish": "¿A qué hora abren?", "english": "What time do you open?"},
{"spanish": "¿A qué hora cierran?", "english": "What time do you close?"},
{"spanish": "Quiero ir allí", "english": "I want to go there"},
{"spanish": "Estoy buscando...", "english": "I am looking for..."},
{"spanish": "Me gusta", "english": "I like it"},
{"spanish": "No me gusta", "english": "I don't like it"},
{"spanish": "Estoy de acuerdo", "english": "I agree"},
{"spanish": "No estoy de acuerdo", "english": "I disagree"},
{"spanish": "Es demasiado caro", "english": "It’s too expensive"},
{"spanish": "Es barato", "english": "It’s cheap"},
{"spanish": "¿Puedo pagar con tarjeta?", "english": "Can I pay by card?"},
{"spanish": "Necesito ayuda", "english": "I need help"},
{"spanish": "¿Qué pasa?", "english": "What's happening?"},
{"spanish": "Todo está bien", "english": "Everything is fine"},
{"spanish": "Nos vemos mañana", "english": "See you tomorrow"},
{"spanish": "¿Tienes Wi-Fi?", "english": "Do you have Wi-Fi?"},
{"spanish": "No funciona", "english": "It doesn’t work"},
{"spanish": "¡Felicidades!", "english": "Congratulations!"},
{"spanish": "Salud", "english": "Bless you (or Cheers)"},
{"spanish": "Perdón", "english": "Pardon"},
{"spanish": "¿Puedes hablar más despacio?", "english": "Can you speak slower?"},
{"spanish": "¿Qué significa...?", "english": "What does ... mean?"},
{"spanish": "Tengo frío", "english": "I’m cold"},
{"spanish": "Tengo calor", "english": "I’m hot"},
{"spanish": "¿Puedo sentarme aquí?", "english": "Can I sit here?"},
{"spanish": "Está bien", "english": "It’s okay"},
{"spanish": "¿Dónde está...?", "english": "Where is ...?"},
{"spanish": "¿Puedes mostrarme?", "english": "Can you show me?"},
{"spanish": "Quiero comprar esto", "english": "I want to buy this"},
{"spanish": "¿Me puedes dar la cuenta?", "english": "Can you give me the bill?"},
{"spanish": "Me llamo", "english": "My name is"},
{"spanish": "Te extraño", "english": "I miss you"},
{"spanish": "Me siento mal", "english": "I feel bad"},
{"spanish": "Vamos", "english": "Let’s go"},
{"spanish": "¿Qué quieres hacer?", "english": "What do you want to do?"},
{"spanish": "No puedo", "english": "I can’t"},
{"spanish": "¿Cuándo es...?", "english": "When is...?"},
{"spanish": "¿Puedes ayudarme?", "english": "Can you help me?"},
{"spanish": "¿Cuántos años tienes?", "english": "How old are you?"},
{"spanish": "Tengo... años", "english": "I am ... years old"},
{"spanish": "Estoy ocupado/a", "english": "I am busy"},
{"spanish": "Estoy libre", "english": "I am free"},
{"spanish": "No sé", "english": "I don’t know"},
{"spanish": "Estoy aprendiendo español", "english": "I am learning Spanish"},
{"spanish": "Estoy aquí", "english": "I am here"},
{"spanish": "¿Puedo entrar?", "english": "Can I come in?"},
{"spanish": "No hay problema", "english": "No problem"},
{"spanish": "Esto es delicioso", "english": "This is delicious"},
{"spanish": "Eso es increíble", "english": "That’s amazing"},
{"spanish": "No me acuerdo", "english": "I don’t remember"},
{"spanish": "¿Qué tal?", "english": "How’s it going?"},
{"spanish": "Voy a...", "english": "I’m going to..."},
{"spanish": "Lo haré", "english": "I will do it"},
{"spanish": "¿Dónde puedo encontrar...?", "english": "Where can I find...?"},
{"spanish": "¿Dónde puedo comprar...?", "english": "Where can I buy...?"},
{"spanish": "¿A qué hora es...?", "english": "What time is...?"},
{"spanish": "No tengo", "english": "I don’t have it"},
{"spanish": "Vamos a comer", "english": "Let’s eat"},
{"spanish": "Estoy listo/a", "english": "I’m ready"},
{"spanish": "No puedo esperar", "english": "I can’t wait"},
{"spanish": "Es mi turno", "english": "It’s my turn"},
{"spanish": "¿Puedo ayudarte?", "english": "Can I help you?"},
{"spanish": "¿Te gusta...?", "english": "Do you like...?"},
{"spanish": "¡Cuidado!", "english": "Be careful!"},
{"spanish": "No te preocupes", "english": "Don’t worry"},
{"spanish": "Espero que sí", "english": "I hope so"},
{"spanish": "Lo sé", "english": "I know"},
{"spanish": "No lo sé", "english": "I don’t know"},
{"spanish": "¡Buena suerte!", "english": "Good luck!"},
{"spanish": "¡Buen provecho!", "english": "Enjoy your meal!"},
{"spanish": "¡Qué bonito!", "english": "How beautiful!"},
{"spanish": "Hablar", "english": "To talk/speak"},
{"spanish": "Comer", "english": "To eat"},
{"spanish": "Vivir", "english": "To live"},
{"spanish": "Ser", "english": "To be (permanent)"},
{"spanish": "Estar", "english": "To be (temporary)"},
{"spanish": "Hacer", "english": "To do/make"},
{"spanish": "Ir", "english": "To go"},
{"spanish": "Tener", "english": "To have"},
{"spanish": "Venir", "english": "To come"},
{"spanish": "Poder", "english": "To be able to"},
{"spanish": "Decir", "english": "To say/tell"},
{"spanish": "Ver", "english": "To see"},
{"spanish": "Dar", "english": "To give"},
{"spanish": "Saber", "english": "To know (facts)"},
{"spanish": "Querer", "english": "To want/love"},
{"spanish": "Llegar", "english": "To arrive"},
{"spanish": "Pasar", "english": "To happen/pass"},
{"spanish": "Deber", "english": "Should/must"},
{"spanish": "Poner", "english": "To put/place"},
{"spanish": "Parecer", "english": "To seem"},
{"spanish": "Quedar", "english": "To stay/remain"},
{"spanish": "Creer", "english": "To believe"},
{"spanish": "Llevar", "english": "To carry/take"},
{"spanish": "Dejar", "english": "To leave/allow"},
{"spanish": "Seguir", "english": "To follow/continue"},
{"spanish": "Encontrar", "english": "To find"},
{"spanish": "Llamar", "english": "To call"},
{"spanish": "Pensar", "english": "To think"},
{"spanish": "Salir", "english": "To leave"},
{"spanish": "Volver", "english": "To return"},
{"spanish": "Tomar", "english": "To take/drink"},
{"spanish": "Conocer", "english": "To meet/know"},
{"spanish": "Sentir", "english": "To feel"},
{"spanish": "Empezar", "english": "To start"},
{"spanish": "Buscar", "english": "To look for"},
{"spanish": "Entrar", "english": "To enter"},
{"spanish": "Trabajar", "english": "To work"},
{"spanish": "Escribir", "english": "To write"},
{"spanish": "Perder", "english": "To lose"},
{"spanish": "Probar", "english": "To try/taste"},
{"spanish": "Pagar", "english": "To pay"},
{"spanish": "Escuchar", "english": "To listen"},
{"spanish": "Cambiar", "english": "To change"},
{"spanish": "Abrir", "english": "To open"},
{"spanish": "Leer", "english": "To read"},
{"spanish": "Ayudar", "english": "To help"},
{"spanish": "Jugar", "english": "To play"},
{"spanish": "Esperar", "english": "To wait"},
{"spanish": "Necesitar", "english": "To need"},
{"spanish": "Estudiar", "english": "To study"},
{"spanish": "Vender", "english": "To sell"},
{"spanish": "Comprar", "english": "To buy"},
{"spanish": "Mirar", "english": "To look/watch"},
{"spanish": "Romper", "english": "To break"},
{"spanish": "Viajar", "english": "To travel"},
{"spanish": "Recibir", "english": "To receive"},
{"spanish": "Ganar", "english": "To win/earn"},
{"spanish": "Contar", "english": "To count/tell"},
{"spanish": "Preguntar", "english": "To ask"},
{"spanish": "Recordar", "english": "To remember"},
{"spanish": "Saltar", "english": "To jump"},
{"spanish": "Mover", "english": "To move"},
{"spanish": "Reír", "english": "To laugh"},
{"spanish": "Caminar", "english": "To walk"},
{"spanish": "Dormir", "english": "To sleep"},
{"spanish": "Buscar", "english": "To search"},
{"spanish": "Despertar", "english": "To wake up"},
{"spanish": "Cerrar", "english": "To close"},
{"spanish": "Cantar", "english": "To sing"},
{"spanish": "Volver", "english": "To return"},
{"spanish": "Aprender", "english": "To learn"},
{"spanish": "Volar", "english": "To fly"},
{"spanish": "Repetir", "english": "To repeat"},
{"spanish": "Lavar", "english": "To wash"},
{"spanish": "Bajar", "english": "To go down"},
{"spanish": "Limpiar", "english": "To clean"},
{"spanish": "Subir", "english": "To go up"},
{"spanish": "Caer", "english": "To fall"},
{"spanish": "Enseñar", "english": "To teach"},
{"spanish": "Cocinar", "english": "To cook"},
{"spanish": "Bailar", "english": "To dance"},
{"spanish": "Romper", "english": "To break"},
{"spanish": "Pensar", "english": "To think"},
{"spanish": "Llorar", "english": "To cry"},
{"spanish": "Volver", "english": "To come back"},
{"spanish": "Escuchar", "english": "To listen"},
{"spanish": "Entender", "english": "To understand"},
{"spanish": "Hacer", "english": "To make/do"},
{"spanish": "Estar", "english": "To be"},
{"spanish": "Pedir", "english": "To ask for/order"},
{"spanish": "Saber", "english": "To know (information)"},
{"spanish": "Conocer", "english": "To know (a person or place)"},
{"spanish": "Dejar", "english": "To leave/allow"},
{"spanish": "Venir", "english": "To come"},
{"spanish": "Querer", "english": "To want/love"},
{"spanish": "Poder", "english": "To be able to"},
{"spanish": "Saber", "english": "To know (facts, information)"},
{"spanish": "Conocer", "english": "To know (a person or place)"},
{"spanish": "Parecer", "english": "To seem"},
{"spanish": "Tener", "english": "To have"},
{"spanish": "Dejar", "english": "To leave/allow"},
{"spanish": "Seguir", "english": "To follow/continue"},
{"spanish": "Poner", "english": "To put/place"},
{"spanish": "Quedar", "english": "To stay/remain"},
{"spanish": "Dar", "english": "To give"},
{"spanish": "Decir", "english": "To say/tell"},
{"spanish": "Venir", "english": "To come"},
{"spanish": "Llamar", "english": "To call"},
{"spanish": "Sentir", "english": "To feel"},
{"spanish": "Volver", "english": "To return"},
{"spanish": "Salir", "english": "To go out/leave"},
{"spanish": "Llegar", "english": "To arrive"},
{"spanish": "Buscar", "english": "To look for"},
{"spanish": "Llevar", "english": "To carry/wear"},
{"spanish": "Preguntar", "english": "To ask"},
{"spanish": "Creer", "english": "To believe"},
{"spanish": "Pasar", "english": "To pass (time)/happen"},
{"spanish": "Contar", "english": "To count/tell"},
{"spanish": "Esperar", "english": "To wait/hope"},
{"spanish": "Terminar", "english": "To finish"},
{"spanish": "Necesitar", "english": "To need"},
{"spanish": "Comenzar", "english": "To begin/start"},
{"spanish": "Gustar", "english": "To like"},
{"spanish": "Importar", "english": "To matter"},
{"spanish": "Probar", "english": "To try/test"},
{"spanish": "Ser", "english": "To be (permanent)"},
{"spanish": "Estar", "english": "To be (temporary)"},
{"spanish": "Trabajar", "english": "To work"},
{"spanish": "Escribir", "english": "To write"},
{"spanish": "Leer", "english": "To read"},
{"spanish": "Escuchar", "english": "To listen"},
{"spanish": "Oír", "english": "To hear"},
{"spanish": "Ver", "english": "To see/watch"},
{"spanish": "Pagar", "english": "To pay"},
{"spanish": "Vender", "english": "To sell"},
{"spanish": "Comprar", "english": "To buy"},
{"spanish": "Tomar", "english": "To take/drink"},
{"spanish": "Beber", "english": "To drink"},
{"spanish": "Dormir", "english": "To sleep"},
{"spanish": "Correr", "english": "To run"},
{"spanish": "Caminar", "english": "To walk"},
{"spanish": "Saltar", "english": "To jump"},
{"spanish": "Caer", "english": "To fall"},
{"spanish": "Limpiar", "english": "To clean"},
{"spanish": "Barrer", "english": "To sweep"},
{"spanish": "Cocinar", "english": "To cook"},
{"spanish": "Cortar", "english": "To cut"},
{"spanish": "Pintar", "english": "To paint"},
{"spanish": "Abrir", "english": "To open"},
{"spanish": "Cerrar", "english": "To close"},
{"spanish": "Encender", "english": "To turn on/light"},
{"spanish": "Apagar", "english": "To turn off"},
{"spanish": "Salir", "english": "To leave"},
{"spanish": "Entrar", "english": "To enter"},
{"spanish": "Nadar", "english": "To swim"},
{"spanish": "Cantar", "english": "To sing"},
{"spanish": "Bailar", "english": "To dance"},
{"spanish": "Llorar", "english": "To cry"},
{"spanish": "Reír", "english": "To laugh"},
{"spanish": "Sonreír", "english": "To smile"},
{"spanish": "Pensar", "english": "To think"},
{"spanish": "Aprender", "english": "To learn"},
{"spanish": "Enseñar", "english": "To teach"},
{"spanish": "Ayudar", "english": "To help"},
{"spanish": "Ganar", "english": "To win/earn"},
{"spanish": "Perder", "english": "To lose"},
{"spanish": "Buscar", "english": "To search/look for"},
{"spanish": "Conseguir", "english": "To get/obtain"},
{"spanish": "Encontrar", "english": "To find"},
{"spanish": "Observar", "english": "To observe"},
{"spanish": "Explicar", "english": "To explain"},
{"spanish": "Preguntar", "english": "To ask"},
{"spanish": "Responder", "english": "To answer"},
{"spanish": "Contestar", "english": "To reply"},
{"spanish": "Necessitar", "english": "To need"},
{"spanish": "Querer", "english": "To want"},
{"spanish": "Amar", "english": "To love"},
{"spanish": "Odiar", "english": "To hate"},
{"spanish": "Vivir", "english": "To live"},
{"spanish": "Morir", "english": "To die"},
{"spanish": "Nacer", "english": "To be born"},
{"spanish": "Crecer", "english": "To grow"},
{"spanish": "Recordar", "english": "To remember"},
{"spanish": "Olvidar", "english": "To forget"},
{"spanish": "Traer", "english": "To bring"},
{"spanish": "Llevar", "english": "To carry"},
{"spanish": "Regresar", "english": "To return"},
{"spanish": "Ir", "english": "To go"},
{"spanish": "Quedarse", "english": "To stay"},
{"spanish": "Volver", "english": "To return"},
{"spanish": "Caminar", "english": "To walk"},
{"spanish": "Correr", "english": "To run"},
{"spanish": "Saltar", "english": "To jump"},
{"spanish": "Volar", "english": "To fly"},
{"spanish": "Conducir", "english": "To drive"},
{"spanish": "Montar", "english": "To ride"},
{"spanish": "Sentarse", "english": "To sit down"},
{"spanish": "Levantarse", "english": "To stand up"},
{"spanish": "Dormir", "english": "To sleep"},
{"spanish": "Despertarse", "english": "To wake up"},
{"spanish": "Soñar", "english": "To dream"},
{"spanish": "Comer", "english": "To eat"},
{"spanish": "Beber", "english": "To drink"},
{"spanish": "Cocinar", "english": "To cook"},
{"spanish": "Preparar", "english": "To prepare"},
{"spanish": "Cortar", "english": "To cut"},
{"spanish": "Limpiar", "english": "To clean"},
{"spanish": "Planchar", "english": "To iron"},
{"spanish": "Secar", "english": "To dry"},
{"spanish": "Colgar", "english": "To hang"},
{"spanish": "Doblar", "english": "To fold"},
{"spanish": "Guardar", "english": "To store/put away"},
{"spanish": "Escribir", "english": "To write"},
{"spanish": "Leer", "english": "To read"},
{"spanish": "Estudiar", "english": "To study"},
{"spanish": "Aprender", "english": "To learn"},
{"spanish": "Escuchar", "english": "To listen"},
{"spanish": "Ver", "english": "To see/watch"},
{"spanish": "Observar", "english": "To observe"},
{"spanish": "Explicar", "english": "To explain"},
{"spanish": "Entender", "english": "To understand"},
{"spanish": "Pensar", "english": "To think"},
{"spanish": "Creer", "english": "To believe"},
{"spanish": "Saber", "english": "To know"},
{"spanish": "Conocer", "english": "To know (someone)"},
{"spanish": "Cantar", "english": "To sing"},
{"spanish": "Bailar", "english": "To dance"},
{"spanish": "Jugar", "english": "To play (a game)"},
{"spanish": "Tocar", "english": "To play (an instrument)"},
{"spanish": "Hablar", "english": "To talk/speak"},
{"spanish": "Llamar", "english": "To call"},
{"spanish": "Pensar", "english": "To think"},
{"spanish": "Creer", "english": "To believe"},
{"spanish": "Saber", "english": "To know (information)"},
{"spanish": "Conocer", "english": "To know (a person or place)"},
{"spanish": "Leer", "english": "To read"},
{"spanish": "Escribir", "english": "To write"},
{"spanish": "Escuchar", "english": "To listen"},
{"spanish": "Ver", "english": "To see/watch"},
{"spanish": "Observar", "english": "To observe"},
{"spanish": "Mirar", "english": "To look at"},
{"spanish": "Sentarse", "english": "To sit down"},
{"spanish": "Levantarse", "english": "To stand up"},
{"spanish": "Dormir", "english": "To sleep"},
{"spanish": "Despertarse", "english": "To wake up"},
{"spanish": "Soñar", "english": "To dream"},
{"spanish": "Ir", "english": "To go"},
{"spanish": "Venir", "english": "To come"},
{"spanish": "Llegar", "english": "To arrive"},
{"spanish": "Salir", "english": "To leave"},
{"spanish": "Quedarse", "english": "To stay"},
{"spanish": "Volver", "english": "To return"},
{"spanish": "Viajar", "english": "To travel"},
{"spanish": "Conducir", "english": "To drive"},
{"spanish": "Volar", "english": "To fly"},
{"spanish": "Caminar", "english": "To walk"},
{"spanish": "Correr", "english": "To run"},
{"spanish": "Saltar", "english": "To jump"},
{"spanish": "Nadar", "english": "To swim"},
{"spanish": "Montar", "english": "To ride"},
{"spanish": "Subir", "english": "To go up"},
{"spanish": "Bajar", "english": "To go down"},
{"spanish": "Abrir", "english": "To open"},
{"spanish": "Cerrar", "english": "To close"},
{"spanish": "Encender", "english": "To turn on/light"},
{"spanish": "Apagar", "english": "To turn off"},
{"spanish": "Comprar", "english": "To buy"},
{"spanish": "Vender", "english": "To sell"},
{"spanish": "Pagar", "english": "To pay"},
{"spanish": "Recibir", "english": "To receive"},
{"spanish": "Enviar", "english": "To send"},
{"spanish": "Traer", "english": "To bring"},
{"spanish": "Llevar", "english": "To take"},
{"spanish": "Comer", "english": "To eat"},
{"spanish": "Beber", "english": "To drink"},
{"spanish": "Cocinar", "english": "To cook"},
{"spanish": "Limpiar", "english": "To clean"},
{"spanish": "Lavar", "english": "To wash"},
{"spanish": "Planchar", "english": "To iron"},
{"spanish": "Cortar", "english": "To cut"},
{"spanish": "Reparar", "english": "To repair"},
{"spanish": "Pintar", "english": "To paint"},
{"spanish": "Ganar", "english": "To win/earn"},
{"spanish": "Perder", "english": "To lose"},
{"spanish": "Ayudar", "english": "To help"},
{"spanish": "Encontrar", "english": "To find"},
{"spanish": "Buscar", "english": "To look for"},
{"spanish": "Seguir", "english": "To follow/continue"},
{"spanish": "Dejar", "english": "To leave/allow"},
{"spanish": "Tener", "english": "To have"},
{"spanish": "Hacer", "english": "To do/make"},
{"spanish": "Decir", "english": "To say"},
{"spanish": "Dar", "english": "To give"},
{"spanish": "Preguntar", "english": "To ask"},
{"spanish": "Contestar", "english": "To answer"},
{"spanish": "Entender", "english": "To understand"},
{"spanish": "Explicar", "english": "To explain"},
{"spanish": "Querer", "english": "To want/love"},
{"spanish": "Poder", "english": "To be able to"},
{"spanish": "Estar", "english": "To be (temporary)"},
{"spanish": "Ser", "english": "To be (permanent)"},
{"spanish": "Volver", "english": "To return"},
{"spanish": "Viajar", "english": "To travel"},
{"spanish": "Conducir", "english": "To drive"},
{"spanish": "Montar", "english": "To ride"},
{"spanish": "Llevar", "english": "To take/carry"},
{"spanish": "Traer", "english": "To bring"},
{"spanish": "Quedarse", "english": "To stay"},
{"spanish": "Salir", "english": "To leave"},
{"spanish": "Volver", "english": "To return"},
{"spanish": "Pensar", "english": "To think"},
{"spanish": "Creer", "english": "To believe"},
{"spanish": "Saber", "english": "To know (information)"},
{"spanish": "Conocer", "english": "To know (a person or place)"},
{"spanish": "Poner", "english": "To put"},
{"spanish": "Llamarse", "english": "To call oneself"},
{"spanish": "Sentarse", "english": "To sit down"},
{"spanish": "Levantarse", "english": "To get up"},
{"spanish": "Despertarse", "english": "To wake up"},
{"spanish": "Acostarse", "english": "To go to bed"},
{"spanish": "Ducharse", "english": "To shower"},
{"spanish": "Bañarse", "english": "To bathe"},
{"spanish": "Lavarse", "english": "To wash oneself"},
{"spanish": "Cepillarse", "english": "To brush (hair/teeth)"},
{"spanish": "Peinarse", "english": "To comb one's hair"},
{"spanish": "Maquillarse", "english": "To put on makeup"},
{"spanish": "Vestirse", "english": "To get dressed"},
{"spanish": "Quitarse", "english": "To take off (clothes)"},
{"spanish": "Afeitarse", "english": "To shave"},
{"spanish": "Secarse", "english": "To dry oneself"},
{"spanish": "Ponerse", "english": "To put on (clothes)"},
{"spanish": "Divertirse", "english": "To have fun"},
{"spanish": "Aburrirse", "english": "To get bored"},
{"spanish": "Enfermarse", "english": "To get sick"},
{"spanish": "Enamorarse", "english": "To fall in love"},
{"spanish": "Casarse", "english": "To get married"},
{"spanish": "Enojarse", "english": "To get angry"},
{"spanish": "Asustarse", "english": "To get scared"},
{"spanish": "Preocuparse", "english": "To worry"},
{"spanish": "Acordarse", "english": "To remember"},
{"spanish": "Equivocarse", "english": "To make a mistake"},
{"spanish": "Perderse", "english": "To get lost"},
{"spanish": "Encontrarse", "english": "To meet up with someone"},
{"spanish": "Acercarse", "english": "To approach"},
{"spanish": "Alejarse", "english": "To move away"},
{"spanish": "Caerse", "english": "To fall down"},
{"spanish": "Quedarse", "english": "To stay"},
{"spanish": "Mudarse", "english": "To move (residence)"},
{"spanish": "Parecer", "english": "To seem"},
{"spanish": "Parecerse", "english": "To look like"},
{"spanish": "Llevarse bien", "english": "To get along well"},
{"spanish": "Llevarse mal", "english": "To not get along"},
{"spanish": "Casarse con", "english": "To marry (someone)"},
{"spanish": "Divorciarse de", "english": "To divorce (someone)"},
{"spanish": "Morirse", "english": "To die (emphasized)"},
{"spanish": "Disculparse", "english": "To apologize"},
{"spanish": "Atreverse", "english": "To dare"},
{"spanish": "Olvidarse de", "english": "To forget about"},
{"spanish": "Darse cuenta", "english": "To realize"},
{"spanish": "Imaginarse", "english": "To imagine"},
{"spanish": "Ponerse de pie", "english": "To stand up"},
{"spanish": "Meterse", "english": "To get into"},
{"spanish": "Arrepentirse", "english": "To regret"},
{"spanish": "Dormirse", "english": "To fall asleep"},
{"spanish": "Cansarse", "english": "To get tired"},
{"spanish": "Enfadarse", "english": "To get mad"},
{"spanish": "Alegrarse", "english": "To be happy"},
{"spanish": "Sorprenderse", "english": "To be surprised"},
{"spanish": "Sentirse", "english": "To feel (emotion/health)"},
{"spanish": "Romperse", "english": "To break (a bone)"},
{"spanish": "Lastimarse", "english": "To hurt oneself"},
{"spanish": "Caerse bien", "english": "To like someone (non-romantic)"},
{"spanish": "Caerse mal", "english": "To dislike someone"},
{"spanish": "Quedarse dormido", "english": "To oversleep"},
{"spanish": "Volverse loco", "english": "To go crazy"},
{"spanish": "Equivocarse de camino", "english": "To take the wrong path"},
{"spanish": "Concentrarse", "english": "To focus"},
{"spanish": "Burlarse de", "english": "To make fun of"},
{"spanish": "Relajarse", "english": "To relax"},
{"spanish": "Fijarse en", "english": "To notice"},
{"spanish": "Aburrirse de", "english": "To get bored of"},
{"spanish": "Preocuparse por", "english": "To worry about"},
{"spanish": "Dedicarse a", "english": "To devote oneself to"},
{"spanish": "Esforzarse por", "english": "To make an effort to"},
{"spanish": "Quedarse sin", "english": "To run out of"},
{"spanish": "Apurarse", "english": "To hurry"},
{"spanish": "Acostumbrarse a", "english": "To get used to"},
{"spanish": "Ocuparse de", "english": "To take care of"},
{"spanish": "Aprovecharse de", "english": "To take advantage of"},
{"spanish": "Quejarse de", "english": "To complain about"},
{"spanish": "Reirse de", "english": "To laugh at"},
{"spanish": "Cuidarse", "english": "To take care of oneself"},
{"spanish": "Divorciarse de", "english": "To get divorced from"},
{"spanish": "Hacerse amigo de", "english": "To become friends with"},
{"spanish": "Fingir", "english": "To pretend"},
{"spanish": "Hacerse", "english": "To become (profession)"},
{"spanish": "Ponerse enfermo", "english": "To get sick"},
{"spanish": "Aclararse", "english": "To get clearer"},
{"spanish": "Acertar", "english": "To get it right"},
{"spanish": "Adelgazar", "english": "To lose weight"},
{"spanish": "Ahorcarse", "english": "To hang oneself"},
{"spanish": "Alegrarse de", "english": "To be happy about"},
{"spanish": "Aprobar", "english": "To pass (a test)"},
{"spanish": "Borrar", "english": "To erase"},
{"spanish": "Coger", "english": "To grab/take"},
{"spanish": "Contar", "english": "To count/tell"},
{"spanish": "Crecer", "english": "To grow"},
{"spanish": "Deber", "english": "To owe/should"},
{"spanish": "Dejar de", "english": "To stop (doing something)"},
{"spanish": "Descansar", "english": "To rest"},
{"spanish": "Devolver", "english": "To return (an item)"},
{"spanish": "Disfrutar de", "english": "To enjoy"},
{"spanish": "Encantar", "english": "To love (something)"},
{"spanish": "Encontrar", "english": "To find"},
{"spanish": "Faltar", "english": "To be missing/lacking"},
{"spanish": "Gustar", "english": "To like"},
{"spanish": "Hacer falta", "english": "To need"},
{"spanish": "Importar", "english": "To matter"},
{"spanish": "Interesar", "english": "To interest"},
{"spanish": "Llover", "english": "To rain"},
{"spanish": "Nevar", "english": "To snow"},
{"spanish": "Odiar", "english": "To hate"},
{"spanish": "Olvidar", "english": "To forget"},
{"spanish": "Parecer", "english": "To seem"},
{"spanish": "Pedir", "english": "To ask for/order"},
{"spanish": "Pensar", "english": "To think"},
{"spanish": "Perder", "english": "To lose"},
{"spanish": "Poder", "english": "To be able to"},
{"spanish": "Preferir", "english": "To prefer"},
{"spanish": "Probar", "english": "To try/test"},
{"spanish": "Quedar", "english": "To stay"},
{"spanish": "Querer", "english": "To want/love"},
{"spanish": "Recomendar", "english": "To recommend"},
{"spanish": "Reír", "english": "To laugh"},
{"spanish": "Romper", "english": "To break"},
{"spanish": "Sentir", "english": "To feel"},
{"spanish": "Tener que", "english": "To have to"},
{"spanish": "Traer", "english": "To bring"},
{"spanish": "Venir", "english": "To come"},
{"spanish": "Volver", "english": "To return"},
{"spanish": "Configuración", "english": "Settings"},
{"spanish": "Idioma", "english": "Language"},
{"spanish": "Pantalla", "english": "Display"},
{"spanish": "Brillo", "english": "Brightness"},
{"spanish": "Sonido", "english": "Sound"},
{"spanish": "Notificaciones", "english": "Notifications"},
{"spanish": "Batería", "english": "Battery"},
{"spanish": "Conexiones", "english": "Connections"},
{"spanish": "Almacenamiento", "english": "Storage"},
{"spanish": "Seguridad", "english": "Security"},
{"spanish": "Contraseña", "english": "Password"},
{"spanish": "Actualizaciones", "english": "Updates"},
{"spanish": "Aplicaciones", "english": "Applications (Apps)"},
{"spanish": "Permisos", "english": "Permissions"},
{"spanish": "Desinstalar", "english": "Uninstall"},
{"spanish": "Forzar detención", "english": "Force Stop"},
{"spanish": "Wi-Fi", "english": "Wi-Fi"},
{"spanish": "Datos móviles", "english": "Mobile Data"},
{"spanish": "Bluetooth", "english": "Bluetooth"},
{"spanish": "Modo avión", "english": "Airplane Mode"},
{"spanish": "Punto de acceso", "english": "Hotspot"},
{"spanish": "Red móvil", "english": "Mobile Network"},
{"spanish": "Bloqueo de pantalla", "english": "Screen Lock"},
{"spanish": "Fondo de pantalla", "english": "Wallpaper"},
{"spanish": "Tema", "english": "Theme"},
{"spanish": "Teclado", "english": "Keyboard"},
{"spanish": "Iconos", "english": "Icons"},
{"spanish": "Rotación automática", "english": "Auto-Rotate"},
{"spanish": "Privacidad", "english": "Privacy"},
{"spanish": "Huella digital", "english": "Fingerprint"},
{"spanish": "Reconocimiento facial", "english": "Facial Recognition"},
{"spanish": "Encriptación", "english": "Encryption"},
{"spanish": "Cámara", "english": "Camera"},
{"spanish": "Galería", "english": "Gallery"},
{"spanish": "Archivos", "english": "Files"},
{"spanish": "Navegador", "english": "Browser"},
{"spanish": "Correo", "english": "Email"},
{"spanish": "Modo oscuro", "english": "Dark Mode"},
{"spanish": "Hora", "english": "Time"},
{"spanish": "Reiniciar", "english": "Restart"},
{"spanish": "Apagar", "english": "Power Off"},
{"spanish": "Sonido de llamada", "english": "Ringtone"},
{"spanish": "Vibración", "english": "Vibration"},
{"spanish": "Multimedia", "english": "Multimedia"},
{"spanish": "Ajustes avanzados", "english": "Advanced Settings"},
{"spanish": "Seguridad y emergencia", "english": "Security and Emergency"},
{"spanish": "Cuentas", "english": "Accounts"},
{"spanish": "Restablecer", "english": "Reset"},
{"spanish": "Sincronización", "english": "Sync"},
{"spanish": "Copias de seguridad", "english": "Backup"},
{"spanish": "Hola, ¿cómo estás?", "english": "Hello, how are you?"},
{"spanish": "Buenos días", "english": "Good morning"},
{"spanish": "Buenas tardes", "english": "Good afternoon"},
{"spanish": "Buenas noches", "english": "Good evening/night"},
{"spanish": "Gracias", "english": "Thank you"},
{"spanish": "De nada", "english": "You're welcome"},
{"spanish": "Por favor", "english": "Please"},
{"spanish": "Lo siento", "english": "I'm sorry"},
{"spanish": "Disculpe", "english": "Excuse me"},
{"spanish": "No entiendo", "english": "I don't understand"},
{"spanish": "¿Puede repetir?", "english": "Can you repeat?"},
{"spanish": "¿Dónde está el baño?", "english": "Where is the bathroom?"},
{"spanish": "¿Cuánto cuesta?", "english": "How much does it cost?"},
{"spanish": "¿Habla inglés?", "english": "Do you speak English?"},
{"spanish": "No hablo español", "english": "I don't speak Spanish"},
{"spanish": "Ayuda, por favor", "english": "Help, please"},
{"spanish": "Estoy perdido/a", "english": "I'm lost"},
{"spanish": "¿Qué hora es?", "english": "What time is it?"},
{"spanish": "Hasta luego", "english": "See you later"},
{"spanish": "Adiós", "english": "Goodbye"},
{"spanish": "Te quiero", "english": "I love you"},
{"spanish": "¿Cómo te llamas?", "english": "What is your name?"},
{"spanish": "Me llamo...", "english": "My name is..."},
{"spanish": "¿De dónde eres?", "english": "Where are you from?"},
{"spanish": "Soy de...", "english": "I'm from..."},
{"spanish": "Tengo hambre", "english": "I'm hungry"},
{"spanish": "Tengo sed", "english": "I'm thirsty"},
{"spanish": "Estoy cansado/a", "english": "I'm tired"},
{"spanish": "Estoy feliz", "english": "I'm happy"},
{"spanish": "Estoy triste", "english": "I'm sad"},
{"spanish": "¿Puedes ayudarme?", "english": "Can you help me?"},
{"spanish": "¿A qué hora abren?", "english": "What time do you open?"},
{"spanish": "¿A qué hora cierran?", "english": "What time do you close?"},
{"spanish": "Quiero ir allí", "english": "I want to go there"},
{"spanish": "Estoy buscando...", "english": "I am looking for..."},
{"spanish": "Me gusta", "english": "I like it"},
{"spanish": "No me gusta", "english": "I don't like it"},
{"spanish": "Estoy de acuerdo", "english": "I agree"},
{"spanish": "No estoy de acuerdo", "english": "I disagree"},
{"spanish": "Es demasiado caro", "english": "It’s too expensive"},
{"spanish": "Es barato", "english": "It’s cheap"},
{"spanish": "¿Puedo pagar con tarjeta?", "english": "Can I pay by card?"},
{"spanish": "Necesito ayuda", "english": "I need help"},
{"spanish": "¿Qué pasa?", "english": "What's happening?"},
{"spanish": "Todo está bien", "english": "Everything is fine"},
{"spanish": "Nos vemos mañana", "english": "See you tomorrow"},
{"spanish": "¿Tienes Wi-Fi?", "english": "Do you have Wi-Fi?"},
{"spanish": "No funciona", "english": "It doesn’t work"},
{"spanish": "¡Felicidades!", "english": "Congratulations!"},
{"spanish": "Salud", "english": "Bless you (or Cheers)"},
{"spanish": "Perdón", "english": "Pardon"},
{"spanish": "¿Puedes hablar más despacio?", "english": "Can you speak slower?"},
{"spanish": "¿Qué significa...?", "english": "What does ... mean?"},
{"spanish": "Tengo frío", "english": "I’m cold"},
{"spanish": "Tengo calor", "english": "I’m hot"},
{"spanish": "¿Puedo sentarme aquí?", "english": "Can I sit here?"},
{"spanish": "Está bien", "english": "It’s okay"},
{"spanish": "¿Dónde está...?", "english": "Where is ...?"},
{"spanish": "¿Puedes mostrarme?", "english": "Can you show me?"},
{"spanish": "Quiero comprar esto", "english": "I want to buy this"},
{"spanish": "¿Me puedes dar la cuenta?", "english": "Can you give me the bill?"},
{"spanish": "Me llamo", "english": "My name is"},
{"spanish": "Te extraño", "english": "I miss you"},
{"spanish": "Me siento mal", "english": "I feel bad"},
{"spanish": "Vamos", "english": "Let’s go"},
{"spanish": "¿Qué quieres hacer?", "english": "What do you want to do?"},
{"spanish": "No puedo", "english": "I can’t"},
{"spanish": "¿Cuándo es...?", "english": "When is...?"},
{"spanish": "¿Cuántos años tienes?", "english": "How old are you?"},
{"spanish": "Tengo... años", "english": "I am ... years old"},
{"spanish": "Estoy ocupado/a", "english": "I am busy"},
{"spanish": "Estoy libre", "english": "I am free"},
{"spanish": "No sé", "english": "I don’t know"},
{"spanish": "Estoy aprendiendo español", "english": "I am learning Spanish"},
{"spanish": "Estoy aquí", "english": "I am here"},
{"spanish": "¿Puedo entrar?", "english": "Can I come in?"},
{"spanish": "No hay problema", "english": "No problem"},
{"spanish": "Esto es delicioso", "english": "This is delicious"},
{"spanish": "Eso es increíble", "english": "That’s amazing"},
{"spanish": "No me acuerdo", "english": "I don’t remember"},
{"spanish": "¿Qué tal?", "english": "How’s it going?"},
{"spanish": "Voy a...", "english": "I’m going to..."},
{"spanish": "Lo haré", "english": "I will do it"},
{"spanish": "¿Dónde puedo encontrar...?", "english": "Where can I find...?"},
{"spanish": "¿Dónde puedo comprar...?", "english": "Where can I buy...?"},
{"spanish": "¿A qué hora es...?", "english": "What time is...?"},
{"spanish": "No tengo", "english": "I don’t have it"},
{"spanish": "Vamos a comer", "english": "Let’s eat"},
{"spanish": "Estoy listo/a", "english": "I’m ready"},
{"spanish": "No puedo esperar", "english": "I can’t wait"},
{"spanish": "Es mi turno", "english": "It’s my turn"},
{"spanish": "¿Puedo ayudarte?", "english": "Can I help you?"},
{"spanish": "¿Te gusta...?", "english": "Do you like...?"},
{"spanish": "¡Cuidado!", "english": "Be careful!"},
{"spanish": "No te preocupes", "english": "Don’t worry"},
{"spanish": "Espero que sí", "english": "I hope so"},
{"spanish": "Lo sé", "english": "I know"},
{"spanish": "No lo sé", "english": "I don’t know"},
{"spanish": "¡Buena suerte!", "english": "Good luck!"},
{"spanish": "¡Buen provecho!", "english": "Enjoy your meal!"},
{"spanish": "¡Qué bonito!", "english": "How beautiful!"},
{"spanish": "Hablar", "english": "To talk/speak"},
{"spanish": "Comer", "english": "To eat"},
{"spanish": "Vivir", "english": "To live"},
{"spanish": "Ser", "english": "To be (permanent)"},
{"spanish": "Estar", "english": "To be (temporary)"},
{"spanish": "Hacer", "english": "To do/make"},
{"spanish": "Ir", "english": "To go"},
{"spanish": "Tener", "english": "To have"},
{"spanish": "Venir", "english": "To come"},
{"spanish": "Poder", "english": "To be able to"},
{"spanish": "Decir", "english": "To say/tell"},
{"spanish": "Ver", "english": "To see"},
{"spanish": "Dar", "english": "To give"},
{"spanish": "Saber", "english": "To know (facts)"},
{"spanish": "Querer", "english": "To want/love"},
{"spanish": "Llegar", "english": "To arrive"},
{"spanish": "Pasar", "english": "To happen/pass"},
{"spanish": "Deber", "english": "Should/must"},
{"spanish": "Poner", "english": "To put/place"},
{"spanish": "Parecer", "english": "To seem"},
{"spanish": "Quedar", "english": "To stay/remain"},
{"spanish": "Creer", "english": "To believe"},
{"spanish": "Llevar", "english": "To carry/take"},
{"spanish": "Dejar", "english": "To leave/allow"},
{"spanish": "Seguir", "english": "To follow/continue"},
{"spanish": "Encontrar", "english": "To find"},
{"spanish": "Llamar", "english": "To call"},
{"spanish": "Pensar", "english": "To think"},
{"spanish": "Salir", "english": "To leave"},
{"spanish": "Volver", "english": "To return"},
{"spanish": "Tomar", "english": "To take/drink"},
{"spanish": "Conocer", "english": "To meet/know"},
{"spanish": "Sentir", "english": "To feel"},
{"spanish": "Empezar", "english": "To start"},
{"spanish": "Buscar", "english": "To look for"},
{"spanish": "Entrar", "english": "To enter"},
{"spanish": "Trabajar", "english": "To work"},
{"spanish": "Escribir", "english": "To write"},
{"spanish": "Perder", "english": "To lose"},
{"spanish": "Probar", "english": "To try/taste"},
{"spanish": "Pagar", "english": "To pay"},
{"spanish": "Escuchar", "english": "To listen"},
{"spanish": "Cambiar", "english": "To change"},
{"spanish": "Abrir", "english": "To open"},
{"spanish": "Leer", "english": "To read"},
{"spanish": "Ayudar", "english": "To help"},
{"spanish": "Jugar", "english": "To play"},
{"spanish": "Esperar", "english": "To wait"},
{"spanish": "Necesitar", "english": "To need"},
{"spanish": "Estudiar", "english": "To study"},
{"spanish": "Vender", "english": "To sell"},
{"spanish": "Comprar", "english": "To buy"},
{"spanish": "Mirar", "english": "To look/watch"},
{"spanish": "Romper", "english": "To break"},
{"spanish": "Viajar", "english": "To travel"},
{"spanish": "Recibir", "english": "To receive"},
{"spanish": "Ganar", "english": "To win/earn"},
{"spanish": "Contar", "english": "To count/tell"},
{"spanish": "Salir", "english": "To go out/leave"},
{"spanish": "Preguntar", "english": "To ask"},
{"spanish": "Recordar", "english": "To remember"},
{"spanish": "Saltar", "english": "To jump"},
{"spanish": "Mover", "english": "To move"},
{"spanish": "Reír", "english": "To laugh"},
{"spanish": "Correr", "english": "To run"},
{"spanish": "Caminar", "english": "To walk"},
{"spanish": "Dormir", "english": "To sleep"},
{"spanish": "Buscar", "english": "To search"},
{"spanish": "Llevar", "english": "To wear/carry"},
{"spanish": "Despertar", "english": "To wake up"},
{"spanish": "Cerrar", "english": "To close"},
{"spanish": "Cantar", "english": "To sing"},
{"spanish": "Aprender", "english": "To learn"},
{"spanish": "Volar", "english": "To fly"},
{"spanish": "Repetir", "english": "To repeat"},
{"spanish": "Lavar", "english": "To wash"},
{"spanish": "Sacar", "english": "To take out"},
{"spanish": "Bajar", "english": "To go down"},
{"spanish": "Limpiar", "english": "To clean"},
{"spanish": "Subir", "english": "To go up"},
{"spanish": "Borrar", "english": "To erase"},
{"spanish": "Caer", "english": "To fall"},
{"spanish": "Gritar", "english": "To scream"},
{"spanish": "Enseñar", "english": "To teach"},
{"spanish": "Cocinar", "english": "To cook"},
{"spanish": "Bailar", "english": "To dance"},
{"spanish": "Regalar", "english": "To give a gift"},
{"spanish": "Soñar", "english": "To dream"},
{"spanish": "Viajar", "english": "To travel"},
{"spanish": "Contar", "english": "To count/tell"},
{"spanish": "Romper", "english": "To break"},
{"spanish": "Enamorarse", "english": "To fall in love"},
{"spanish": "Llorar", "english": "To cry"},
{"spanish": "Escuchar", "english": "To listen"},
{"spanish": "Entender", "english": "To understand"},
{"spanish": "Hacer", "english": "To make/do"},
{"spanish": "Pedir", "english": "To ask for/order"},
{"spanish": "Repetir", "english": "To repeat"},
{"spanish": "Subir", "english": "To go up/ascend"},
{"spanish": "Bajar", "english": "To go down/descend"},
{"spanish": "Poder", "english": "To be able to"},
{"spanish": "Saber", "english": "To know (information)"},
{"spanish": "Conocer", "english": "To know (a person, place)"},
{"spanish": "Parecer", "english": "To seem"},
{"spanish": "Dejar", "english": "To leave/allow"},
{"spanish": "Seguir", "english": "To follow/continue"},
{"spanish": "Poner", "english": "To put/place"},
{"spanish": "Dar", "english": "To give"},
{"spanish": "Venir", "english": "To come"},
{"spanish": "Llamar", "english": "To call"},
{"spanish": "Sentir", "english": "To feel"},
{"spanish": "Volver", "english": "To return"},
{"spanish": "Llegar", "english": "To arrive"},
{"spanish": "Buscar", "english": "To look for"},
{"spanish": "Preguntar", "english": "To ask"},
{"spanish": "Creer", "english": "To believe"},
{"spanish": "Pasar", "english": "To pass (time)/happen"},
{"spanish": "Esperar", "english": "To wait/hope"},
{"spanish": "Terminar", "english": "To finish"},
{"spanish": "Necesitar", "english": "To need"},
{"spanish": "Comenzar", "english": "To start/begin"},
{"spanish": "Gustar", "english": "To like"},
{"spanish": "Importar", "english": "To matter/care"},
{"spanish": "Probar", "english": "To try/taste"},
{"spanish": "Estudiar", "english": "To study"},
{"spanish": "Trabajar", "english": "To work"},
{"spanish": "Escribir", "english": "To write"},
{"spanish": "Leer", "english": "To read"},
{"spanish": "Jugar", "english": "To play"},
{"spanish": "Ver", "english": "To see"},
{"spanish": "Escuchar", "english": "To listen"},
{"spanish": "Oír", "english": "To hear"},
{"spanish": "Llamar", "english": "To call"},
{"spanish": "Pagar", "english": "To pay"},
{"spanish": "Vender", "english": "To sell"},
{"spanish": "Comprar", "english": "To buy"},
{"spanish": "Tomar", "english": "To take"},
{"spanish": "Beber", "english": "To drink"},
{"spanish": "Dormir", "english": "To sleep"},
{"spanish": "Correr", "english": "To run"},
{"spanish": "Andar", "english": "To walk"},
{"spanish": "Caminar", "english": "To walk"},
{"spanish": "Saltar", "english": "To jump"},
{"spanish": "Caer", "english": "To fall"},
{"spanish": "Limpiar", "english": "To clean"},
{"spanish": "Cocinar", "english": "To cook"},
{"spanish": "Pintar", "english": "To paint"},
{"spanish": "Abrir", "english": "To open"},
{"spanish": "Cerrar", "english": "To close"},
{"spanish": "Encender", "english": "To turn on/light"},
{"spanish": "Apagar", "english": "To turn off"},
{"spanish": "Salir", "english": "To go out"},
{"spanish": "Nadar", "english": "To swim"},
{"spanish": "Cantar", "english": "To sing"},
{"spanish": "Bailar", "english": "To dance"},
{"spanish": "Reír", "english": "To laugh"},
{"spanish": "Soñar", "english": "To dream"},
{"spanish": "Caminar", "english": "To walk"},
{"spanish": "Volver", "english": "To return"},
]


class QuizApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Futuristic Language Quiz")
        self.root.geometry("600x400")
        
        # Set background gradient colors
        self.bg_color1 = "#233142"
        self.bg_color2 = "#455d7a"
        self.root.configure(bg=self.bg_color1)
        
        # Shuffle the words
        self.words = random.sample(words, len(words))
        self.index = 0
        self.score = 0
        
        # Create the futuristic UI components
        self.create_widgets()
        self.display_question()

    def create_widgets(self):
        # Add a futuristic title label
        self.title_label = tk.Label(self.root, text="🌟 Language Learning Quiz 🌟", font=("Helvetica", 22, "bold"), bg=self.bg_color1, fg="#ffcc00")
        self.title_label.pack(pady=20)
        
        # Display the question label with modern styling
        self.question_label = tk.Label(self.root, text="", font=("Futura", 16), bg=self.bg_color1, fg="#f5f5f5")
        self.question_label.pack(pady=10)
        
        # Answer input field with modern styling
        self.answer_entry = tk.Entry(self.root, font=("Futura", 14), width=20, fg="#1f4068", bg="#ffdf6b", bd=2, relief="solid")
        self.answer_entry.pack(pady=10)
        
        # Submit answer button with a futuristic glow effect
        self.submit_button = tk.Button(self.root, text="Submit Answer", command=self.check_answer, font=("Futura", 14), bg="#ffcc00", fg="#1f4068", bd=0, relief="flat", activebackground="#ffdf6b", activeforeground="#1f4068")
        self.submit_button.pack(pady=20)
        
        # Exit button with monastery-style elegance
        self.quit_button = tk.Button(self.root, text="Exit Quiz", command=self.quit_quiz, font=("Futura", 14), bg="#1f4068", fg="#f5f5f5", bd=0, relief="flat", activebackground="#455d7a", activeforeground="#ffcc00")
        self.quit_button.pack(pady=10)
        
        # Feedback and score labels with clean and minimalist styling
        self.feedback_label = tk.Label(self.root, text="", font=("Futura", 14), bg=self.bg_color1, fg="#ffdf6b")
        self.feedback_label.pack(pady=10)
        
        self.score_label = tk.Label(self.root, text="Score: 0", font=("Futura", 14), bg=self.bg_color1, fg="#ffdf6b")
        self.score_label.pack(pady=10)

    def display_question(self):
        if self.index < len(self.words):
            spanish_word = self.words[self.index]["spanish"]
            self.question_label.config(text=f"What is the English translation of '{spanish_word}'?")
            self.answer_entry.delete(0, tk.END)
        else:
            messagebox.showinfo("Quiz Complete", f"Quiz complete! Your final score is {self.score}/{len(self.words)}")
            self.root.quit()

    def check_answer(self):
        user_answer = self.answer_entry.get().strip().lower()
        correct_answer = self.words[self.index]["english"].lower()
        
        if user_answer == correct_answer:
            self.feedback_label.config(text="✅ Correct!", fg="#22b14c")
            self.score += 1
        else:
            self.feedback_label.config(text=f"❌ Incorrect! The correct answer was '{self.words[self.index]['english']}'", fg="#ff0000")
        
        self.index += 1
        self.score_label.config(text=f"Score: {self.score}")
        self.display_question()

    def quit_quiz(self):
        self.root.quit()

# Initialize the tkinter window
root = tk.Tk()
app = QuizApp(root)
root.mainloop()